# Generated by Django 6.0.2 on 2026-03-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(default='24-48 घंटों में', max_length=100),
        ),
    ]
